pipeline {
    agent {
        label 'docker'
    }
    stages {
        stage('.NET Version') {
            agent {
                docker { 
                    image 'dotnet:latest' 
                }
            }
            steps {
                sh 'dotnet --version'
            }
        }
        stage('.NET Build') {
            agent {
                docker { 
                    image 'dotnet:latest' 
                }
            }
            steps {
                sh 'dotnet build'
            }
        }
    }
}